name: Read-blob-api-policy 
on:
  push:
    branches:
      - master
    paths:
      - 'SampleAPI/blob/read-blob.xml'
  workflow_dispatch: # for enabling manual trigger
env:
  API_NAME: 'storage-read' #apim api name
  POLICY_PATH: 'APIM-Policies/SampleAPI/blob'
  BLOB_CONTAINER: 'samplecontainer'
  ENVIRONMENT_NAME: 'dev'
  OPERATION_NAME: 'sampleGet'

jobs:
  deploy_dev:
    runs-on: 'ubuntu-latest'
    environment: Development
    steps:
      - name: Checkout action
        uses: actions/checkout@master
      - name: Update Environment Variables
        shell: pwsh
        run: |
          echo "BLOB_FILE_NAME= Sample/${{env.ENVIRONMENT_NAME}}joke.json" | Out-File FilePath $Env:GITHUB_ENV -Encoding utf 8 -Append 

      - name: apim_policy_stg
        id: apim_policy_stg
        uses: ./pipelines/apim_policy/deploy/stg
        with:
           ad_client: ${{secrets.AD_CLIENT_ID}}
           ad_client_secret: ${{secrets.AD_CLIENT_SECRET}}
           ad_tenant_id: ${{secrets.AD_TENANT_ID}}
           subscription_id: ${{var.SUBCRIPTION_ID}} #from Environment variables
           api_name: ${{env.API_NAME}}
           blob_container_name: ${{env.BLOB_CONTAINER}}
           blob_name: ${{env.BLOB_FILE_NAME}} #dynamically read from previous step
           policy_path: ${{env.POLICY_PATH}}
           environment_name: ${{env.ENVIRONMENT_NAME}}
           apim_operation_name: ${{env.APIM_OPERATION_NAME}}